// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyAoCW7K5f60cIoL08EanBtJTpkYVsklPw0',
    appId: '1:1060042762229:android:5ac298fe18e7ed4ec0a2bc',
    messagingSenderId: '1060042762229',
    projectId: 'sneakersapp-e535c',
    storageBucket: 'sneakersapp-e535c.firebasestorage.app',
  );
}